#!/bin/sh -x
#
# 20081112 mjd@genomics.upenn.edu
# 20090304 mjd@genomics.upenn.edu

function warn () {
  echo $@ 1>&2
}

function die () {
  warn $@
  exit 1
}

if [ "x$CATALINA_HOME" = "x" ] ; then
  die '$CATALINA_HOME unset'
fi

WEBAPPS="$CATALINA_HOME/webapps"
TARGET_DIR="treebase-web"

# Flag to suppress sourre update and rebuilding
update_sources=true
if [ "$1" == "-r" ]; then
  update_sources=false
fi

TOMCAT_URL=http://8ball.sdsc.edu:6666/treebase-web/
VERSIONFILE=treebase-core/src/main/java/org/cipres/treebase/Version.java

# Rebuild the application WAR file, if requested
if $update_sources; then
  cd $HOME/treebase/trunk || die "cd treebase/trunk";
  rm -f $VERSIONFILE
  svn update || die
  mvn clean || die
  
  svnrevision=`svn info | perl -lne 'print $1 if /^Revision: (\d+)/'`
  svnrevision=${svnrevision:-'????'}
  
  svndatestring=`svn info | perl -lne 'print $1 if /^Last Changed Date: (.+)/'`
  svndatestring=${svndatestring:-'????'}
  
  perl -i -lpe 'BEGIN { while ($ARGV[0] =~ /=/) {my($k,$v) = split /=/, shift(), 2; $prop{$k} = $v } } s/##(\w+)##/$prop{$1}/g' "VCSID=$svnrevision" "VCSDATESTRING=$svndatestring" $VERSIONFILE

  touch treebase-web/src/main/webapp/common/footer.jsp
 
  mvn install -Dmaven.test.skip=true
fi

# Stop the server, and make sure it's dead before proceeding
${CATALINA_HOME}/bin/catalina.sh stop
if /usr/bin/GET -d $TOMCAT_URL ; then
  die 'Failed to stop tomcat at $TOMCAT_URL'
fi
  
# destroy the old deployment directory and war file
# and move the new warfile into place
if $update_sources; then
  cd $WEBAPPS && rm -rf $TARGET_DIR && rm -f treebase-web.war
  if cp -v warLocation/treebase-web.war . ; then
    :
  else
    die "Installation failed: no WAR file"
  fi 
fi

# Restart the server, and die if it doesn't start right away
${CATALINA_HOME}/bin/catalina.sh start
sleep 3
if /usr/bin/GET -d $TOMCAT_URL ; then
  :   # okay
else 
  die 'Failed to restart tomcat at $TOMCAT_URL'
fi

# Wait for the server to unpack the warfile and create the application dir
# Then install phyloWidget into the correct destination
phyloWidgetTarget=$WEBAPPS/$TARGET_DIR/test/phylowidget
while [ '!' -d $phyloWidgetTarget ]; do
  sleep 1;
done
cp -pv $HOME/PhyloWidget.jar $phyloWidgetTarget || warn "Couldn't install phyloWidget"

echo "Publish operation complete"

