package org.cipres.treebase.dao.study;

import org.cipres.treebase.dao.AbstractDAOTest;
import org.cipres.treebase.domain.study.StudyStatus;
import org.cipres.treebase.domain.study.StudyStatusHome;
import org.junit.Test;
import static org.junit.Assert.*;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * The class <code>StudyStatusDAOTest</code> contains tests for the class
 * {@link <code>StudyStatusDAO</code>}
 * 
 * @pattern JUnit Test Case
 * @generatedBy CodePro at 4/20/06 3:26 PM
 * @author Jin Ruan
 * 
 * @version $Revision$
 */
public class StudyStatusDAOTest extends AbstractDAOTest {

	private StudyStatusHome mStudyStatusHome;

	/**
	 * Return the StudyStatusHome field.
	 * 
	 * @return StudyStatusHome mStudyStatusHome
	 */
	private StudyStatusHome getStudyStatusHome() {
		return mStudyStatusHome;
	}

	/**
	 * Injected by the super class based on autowiring by type.
	 */
	@Autowired
	public void setStudyStatusHome(StudyStatusHome pNewStudyStatusHome) {
		mStudyStatusHome = pNewStudyStatusHome;
	}

	/**
	 * Run the StudyStatus findStatusInProgress() method test
	 */
@Test
	public void testFindStatusInProgress() {
		String testName = "findInProgress";
		if (logger.isInfoEnabled()) {
			logger.info("\n\t\tRunning Test: " + testName);
		}

		StudyStatusHome fixture = getStudyStatusHome();
		StudyStatus result = fixture.findStatusInProgress();

		// verify
		assertTrue(result != null);
		assertTrue(result.isInProgress());

		if (logger.isInfoEnabled()) {
			logger.info(testName + " verified.");
		}
	}

	/**
	 * Run the StudyStatus findStatusReady() method test
	 */
@Test
	public void testFindStatusReady() {
		String testName = "findStatusReady";
		if (logger.isInfoEnabled()) {
			logger.info("\n\t\tRunning Test: " + testName);
		}

		StudyStatusHome fixture = getStudyStatusHome();
		StudyStatus result = fixture.findStatusReady();

		// verify
		assertTrue(result != null);
		assertTrue(result.isReady());

		if (logger.isInfoEnabled()) {
			logger.info(testName + " verified.");
		}
	}

	/**
	 * Run the StudyStatus findStatusPublished() method test
	 */
@Test
	public void testFindStatusPublished() {
		String testName = "findStatusPublished";
		if (logger.isInfoEnabled()) {
			logger.info("\n\t\tRunning Test: " + testName);
		}

		StudyStatusHome fixture = getStudyStatusHome();
		StudyStatus result = fixture.findStatusPublished();

		// verify
		assertTrue(result != null);
		assertTrue(result.isPublished());

		if (logger.isInfoEnabled()) {
			logger.info(testName + " verified.");
		}
	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase additionalTestNames =
 * assertTrue = false callTestMethod = true createMain = false createSetUp = false createTearDown =
 * false createTestFixture = true createTestStubs = true methods = package =
 * org.cipres.treebase.dao.study package.sourceFolder = treebase-core/src/test/java superclassType =
 * org.springframework.test.AbstractSpringContextTests testCase = StudyStatusDAOTest testClassType =
 * org.cipres.treebase.dao.study.StudyStatusDAO
 */