#!/usr/bin/perl

use CIPRES::TreeBase::DBIUtil;
use Getopt::Std;

getopts('s') or die "Usage: $0 SQL statement on command line";

my $dbh = CIPRES::TreeBase::DBIUtil->dbh
      or die "Couldn't connect to database: " . DBI->errstr;

if ($opt_s) {
    my @statements = split /;[ \t]*\r?\n/, join "", <ARGV>;
    for my $Q (@statements) {
	next unless $Q =~ /\S/;
	print "$Q\n";
	$dbh->do($Q)
	    or die "Couldn't prepare statement:\n\t$Q\n\t" . $dbh->errstr;
    }
} else {
    my $Q = join " ", @ARGV;
    $dbh->do($Q)
	or die "Couldn't prepare statement: " . $dbh->errstr;
}

$dbh->disconnect;
