#!/usr/bin/perl
#  -*- cperl -*-

use CIPRES::TreeBase::DBIUtil;
use Getopt::Std;

my %opt = ();
getopts('', \%opt) or usage();
my ($class, $attr, $val) = @ARGV;
defined($class) && defined($attr) && defined($val) or usage();

my $query = "select $class\_id from $class where $attr = ?";

my $dbh = CIPRES::TreeBase::DBIUtil->dbh
  or die "Couldn't connect to database: " . DBI->errstr;
my $sth = $dbh->prepare($query)
  or die "Couldn't prepare statement: " . $dbh->errstr;
my $rc = $sth->execute($val)
  or die "Couldn't execute statement: " . $dbh->errstr;
my $row;
while (my ($id) = $sth->fetchrow_array) {
     print "$id\n";
}

$dbh->disconnect;

sub usage {
    print "$0 [-n nullsymbol] table id#\n";
    exit 1;
}

