#!/usr/bin/perl                              
#  -*- cperl -*-

use CIPRES::TreeBase::DBIUtil;
use Getopt::Std;

my %opt = (z => 30);
getopts('sz:', \%opt) or usage();

@ARGV || usage();
my $table = shift;

my $dbh = CIPRES::TreeBase::DBIUtil->dbh
  or die "Couldn't connect to database: " . DBI->errstr;
my $sth = $dbh->prepare("select count(*) from $table")
  or die "Couldn't prepare statement: " . $dbh->errstr;
my $rc = $sth->execute()
  or die "Couldn't execute statement: " . $dbh->errstr;
my ($before) = $sth->fetchrow_array;
$sth->finish;
#1 while $sth->fetch;
warn "$before rows\n" unless $opt{s};
sleep $opt{z};
my $rc = $sth->execute()
  or die "Couldn't execute statement: " . $dbh->errstr;
my ($after) = $sth->fetchrow_array;
$sth->finish;
warn "$after rows\n" unless $opt{s};
my $rate = ($after-$before)*60/$opt{z};
printf (($opt{s} ? "%.2f\n" : "%.2f records per minute\n"), $rate);

$dbh->disconnect;
exit;

sub usage {
    print "$0 [-s] [-z time-delay] table-name\n";
    print "  -s : short output format\n";
    exit 1;
}
