#!/usr/bin/perl

use strict;
use CIPRES::TreeBase::DBIUtil;
use Getopt::Std;

my %opt;
getopts('', \%opt) or usage();

my $study_id = shift || usage();

my $dbh = CIPRES::TreeBase::DBIUtil->dbh
  or die "Couldn't connect to database: " . DBI->errstr;

my @phylotree_ids = do {
	my $q = "SELECT phylotree_id from phylotree where study_id = ?";
	@{$dbh->selectcol_arrayref($q, {}, $study_id)};
};

for my $phylotree_id (@phylotree_ids) {
    show_phylotree($phylotree_id);
}

sub show_phylotree {
    my $mid = shift;
    {
	my $q = "select title, nexusfilename from phylotree where phylotree_id = ?";
	my $sth = $dbh->prepare_cached($q);
	$sth->execute($mid);
	my ($title, $nexus) = $sth->fetchrow;
	print "PHYLOTREE $mid '$title' ($nexus)\n";
	$sth->finish;
    }
}



sub usage {
    print "$0 study-id\n";
    exit 1;
}

